/*
 * WARNING: do not edit!
 * Generated by configdata.pm from Configurations/common0.tmpl, Configurations/unix-Makefile.tmpl
 * via Makefile.in
 *
 * Copyright 2016-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_CONFIGURATION_H
# define OPENSSL_CONFIGURATION_H
#ifdef OPENSSL_PRAGMA_ONCE
# pragma once
#endif

# ifdef  __cplusplus
extern "C" {
# endif

# ifdef OPENSSL_ALGORITHM_DEFINES
#  error OPENSSL_ALGORITHM_DEFINES no longer supported
# endif

/*
 * OpenSSL was configured with the following options:
 */

# define OPENSSL_CONFIGURED_API 30000
# ifndef OPENSSL_RAND_SEED_OS
#  define OPENSSL_RAND_SEED_OS
# endif
# ifndef OPENSSL_THREADS
#  define OPENSSL_THREADS
# endif
# ifndef OPENSSL_NO_ACVP_TESTS
#  define OPENSSL_NO_ACVP_TESTS
# endif
# ifndef OPENSSL_NO_AFALGENG
#  define OPENSSL_NO_AFALGENG
# endif
# ifndef OPENSSL_NO_ALT_MEMORY
#  define OPENSSL_NO_ALT_MEMORY
# endif
# ifndef OPENSSL_NO_ASAN
#  define OPENSSL_NO_ASAN
# endif
# ifndef OPENSSL_NO_CMS_SM2
#  define OPENSSL_NO_CMS_SM2
# endif
# ifndef OPENSSL_NO_CRL_MEMPOOL
#  define OPENSSL_NO_CRL_MEMPOOL
# endif
# ifndef OPENSSL_NO_CRYPTO_MDEBUG
#  define OPENSSL_NO_CRYPTO_MDEBUG
# endif
# ifndef OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
#  define OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
# endif
# ifndef OPENSSL_NO_DEVCRYPTOENG
#  define OPENSSL_NO_DEVCRYPTOENG
# endif
# ifndef OPENSSL_NO_DH_IGNORE_STRENGTH
#  define OPENSSL_NO_DH_IGNORE_STRENGTH
# endif
# ifndef OPENSSL_NO_DTO
#  define OPENSSL_NO_DTO
# endif
# ifndef OPENSSL_NO_EC_NISTP_64_GCC_128
#  define OPENSSL_NO_EC_NISTP_64_GCC_128
# endif
# ifndef OPENSSL_NO_EGD
#  define OPENSSL_NO_EGD
# endif
# ifndef OPENSSL_NO_EXTERNAL_TESTS
#  define OPENSSL_NO_EXTERNAL_TESTS
# endif
# ifndef OPENSSL_NO_FIPS_SECURITYCHECKS
#  define OPENSSL_NO_FIPS_SECURITYCHECKS
# endif
# ifndef OPENSSL_NO_FUZZ_AFL
#  define OPENSSL_NO_FUZZ_AFL
# endif
# ifndef OPENSSL_NO_FUZZ_LIBFUZZER
#  define OPENSSL_NO_FUZZ_LIBFUZZER
# endif
# ifndef OPENSSL_NO_GM_CMVP
#  define OPENSSL_NO_GM_CMVP
# endif
# ifndef OPENSSL_NO_GM_DRNG
#  define OPENSSL_NO_GM_DRNG
# endif
# ifndef OPENSSL_NO_GMTLS
#  define OPENSSL_NO_GMTLS
# endif
# ifndef OPENSSL_NO_GMTLS_IGNORE_SUPPORTED_VERSIONS
#  define OPENSSL_NO_GMTLS_IGNORE_SUPPORTED_VERSIONS
# endif
# ifndef OPENSSL_NO_INIT_NO_ATEXIT
#  define OPENSSL_NO_INIT_NO_ATEXIT
# endif
# ifndef OPENSSL_NO_KTLS
#  define OPENSSL_NO_KTLS
# endif
# ifndef OPENSSL_NO_KYBER
#  define OPENSSL_NO_KYBER
# endif
# ifndef OPENSSL_NO_MD2
#  define OPENSSL_NO_MD2
# endif
# ifndef OPENSSL_NO_MSAN
#  define OPENSSL_NO_MSAN
# endif
# ifndef OPENSSL_NO_PKCS7_SM2
#  define OPENSSL_NO_PKCS7_SM2
# endif
# ifndef OPENSSL_NO_PKCS8_SM2
#  define OPENSSL_NO_PKCS8_SM2
# endif
# ifndef OPENSSL_NO_PQC
#  define OPENSSL_NO_PQC
# endif
# ifndef OPENSSL_NO_PQCHYBRID
#  define OPENSSL_NO_PQCHYBRID
# endif
# ifndef OPENSSL_NO_RC5
#  define OPENSSL_NO_RC5
# endif
# ifndef OPENSSL_NO_RECORD_VERSION_COMPAT
#  define OPENSSL_NO_RECORD_VERSION_COMPAT
# endif
# ifndef OPENSSL_NO_SCTP
#  define OPENSSL_NO_SCTP
# endif
# ifndef OPENSSL_NO_SM_TLS1_3
#  define OPENSSL_NO_SM_TLS1_3
# endif
# ifndef OPENSSL_NO_SM2_DECODE
#  define OPENSSL_NO_SM2_DECODE
# endif
# ifndef OPENSSL_NO_SM2_ENCODE
#  define OPENSSL_NO_SM2_ENCODE
# endif
# ifndef OPENSSL_NO_SM2_ENVELOP
#  define OPENSSL_NO_SM2_ENVELOP
# endif
# ifndef OPENSSL_NO_SM2_EXCH
#  define OPENSSL_NO_SM2_EXCH
# endif
# ifndef OPENSSL_NO_SM2_NID_ECPUBLICKEY
#  define OPENSSL_NO_SM2_NID_ECPUBLICKEY
# endif
# ifndef OPENSSL_NO_SM9
#  define OPENSSL_NO_SM9
# endif
# ifndef OPENSSL_NO_SSL_GM_CERT
#  define OPENSSL_NO_SSL_GM_CERT
# endif
# ifndef OPENSSL_NO_TLS_SIGALG_SHA1
#  define OPENSSL_NO_TLS_SIGALG_SHA1
# endif
# ifndef OPENSSL_NO_TRACE
#  define OPENSSL_NO_TRACE
# endif
# ifndef OPENSSL_NO_TTO
#  define OPENSSL_NO_TTO
# endif
# ifndef OPENSSL_NO_UBSAN
#  define OPENSSL_NO_UBSAN
# endif
# ifndef OPENSSL_NO_UNIT_TEST
#  define OPENSSL_NO_UNIT_TEST
# endif
# ifndef OPENSSL_NO_UPLINK
#  define OPENSSL_NO_UPLINK
# endif
# ifndef OPENSSL_NO_WAPI
#  define OPENSSL_NO_WAPI
# endif
# ifndef OPENSSL_NO_WEAK_SSL_CIPHERS
#  define OPENSSL_NO_WEAK_SSL_CIPHERS
# endif
# ifndef OPENSSL_NO_X509_PUBKEY_DECODE_PROV
#  define OPENSSL_NO_X509_PUBKEY_DECODE_PROV
# endif
# ifndef OPENSSL_NO_X509_REQ_EXP_ATTR
#  define OPENSSL_NO_X509_REQ_EXP_ATTR
# endif
# ifndef OPENSSL_NO_STATIC_ENGINE
#  define OPENSSL_NO_STATIC_ENGINE
# endif


/* Generate 80386 code? */
# undef I386_ONLY

/*
 * The following are cipher-specific, but are part of the public API.
 */
# if !defined(OPENSSL_SYS_UEFI) && !defined(__UBOOT__)
#  undef BN_LLONG
/* Only one for the following should be defined */
#  define SIXTY_FOUR_BIT_LONG
#  undef SIXTY_FOUR_BIT
#  undef THIRTY_TWO_BIT
# endif

# define RC4_INT unsigned char

# ifdef  __cplusplus
}
# endif

#endif                          /* OPENSSL_CONFIGURATION_H */
